<?php
/**
 * CreateOrderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SveaInstore;

use PHPUnit\Framework\TestCase;

/**
 * CreateOrderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateOrderRequest
 * @package     SveaInstore
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOrderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateOrderRequest"
     */
    public function testCreateOrderRequest()
    {
    }

    /**
     * Test attribute "merchantOrderNumber"
     */
    public function testPropertyMerchantOrderNumber()
    {
    }

    /**
     * Test attribute "countryCode"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "mobilePhoneNumber"
     */
    public function testPropertyMobilePhoneNumber()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "orderItems"
     */
    public function testPropertyOrderItems()
    {
    }

    /**
     * Test attribute "callbackUri"
     */
    public function testPropertyCallbackUri()
    {
    }

    /**
     * Test attribute "termsUri"
     */
    public function testPropertyTermsUri()
    {
    }

    /**
     * Test attribute "deferredDelivery"
     */
    public function testPropertyDeferredDelivery()
    {
    }

    /**
     * Test attribute "minutesUntilLinkExpires"
     */
    public function testPropertyMinutesUntilLinkExpires()
    {
    }

    /**
     * Test attribute "presetValues"
     */
    public function testPropertyPresetValues()
    {
    }

    /**
     * Test attribute "requireElectronicIdAuthentication"
     */
    public function testPropertyRequireElectronicIdAuthentication()
    {
    }

    /**
     * Test attribute "merchantName"
     */
    public function testPropertyMerchantName()
    {
    }
}
