<?php
/**
 * CustomerInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SveaInstore;

use PHPUnit\Framework\TestCase;

/**
 * CustomerInformationTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerInformation
 * @package     SveaInstore
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerInformation"
     */
    public function testCustomerInformation()
    {
    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "emailAddress"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "mobilePhoneNumber"
     */
    public function testPropertyMobilePhoneNumber()
    {
    }
}
