<?php
/**
 * GetOrderStatusResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SveaInstore;

use PHPUnit\Framework\TestCase;

/**
 * GetOrderStatusResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetOrderStatusResponse
 * @package     SveaInstore
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetOrderStatusResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetOrderStatusResponse"
     */
    public function testGetOrderStatusResponse()
    {
    }

    /**
     * Test attribute "merchantOrderNumber"
     */
    public function testPropertyMerchantOrderNumber()
    {
    }

    /**
     * Test attribute "instoreUiUri"
     */
    public function testPropertyInstoreUiUri()
    {
    }

    /**
     * Test attribute "orderStatus"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "paymentMethodType"
     */
    public function testPropertyPaymentMethodType()
    {
    }

    /**
     * Test attribute "campaignCode"
     */
    public function testPropertyCampaignCode()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "paymentOrderId"
     */
    public function testPropertyPaymentOrderId()
    {
    }

    /**
     * Test attribute "customerInformation"
     */
    public function testPropertyCustomerInformation()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "orderItems"
     */
    public function testPropertyOrderItems()
    {
    }
}
