<?php
/**
 * OrderItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SveaInstore;

use PHPUnit\Framework\TestCase;

/**
 * OrderItemTest Class Doc Comment
 *
 * @category    Class
 * @description OrderItem
 * @package     SveaInstore
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderItem"
     */
    public function testOrderItem()
    {
    }

    /**
     * Test attribute "articleNumber"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "discountPercent"
     */
    public function testPropertyDiscountPercent()
    {
    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "vatPercent"
     */
    public function testPropertyVatPercent()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "rowNumber"
     */
    public function testPropertyRowNumber()
    {
    }

    /**
     * Test attribute "merchantData"
     */
    public function testPropertyMerchantData()
    {
    }
}
