<?php
/**
 * RevokeOrderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SveaInstore;

use PHPUnit\Framework\TestCase;

/**
 * RevokeOrderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description RevokeOrderRequest
 * @package     SveaInstore
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RevokeOrderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RevokeOrderRequest"
     */
    public function testRevokeOrderRequest()
    {
    }

    /**
     * Test attribute "returnedItems"
     */
    public function testPropertyReturnedItems()
    {
    }
}
