<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Svea Webpay Instore Api
 *
 * The Instore API's enables cash registers to create Svea orders that the customer can checkout by following a link sent to them by SMS
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SveaInstore;

use SveaInstore\Configuration;
use SveaInstore\ApiException;
use SveaInstore\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  SveaInstore
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelOrder
     *
     * Cancel the entire order. If the order has been delivered the invoice will be credited..
     *
     */
    public function testCancelOrder()
    {
    }

    /**
     * Test case for createOrder
     *
     * Creates an order. A SMS message will be sent to the provided mobile phone number where the checkout can be completed..
     *
     */
    public function testCreateOrder()
    {
    }

    /**
     * Test case for getOrder
     *
     * Gets order status for a created order. When the order has been finalized customer information is added to the order status response..
     *
     */
    public function testGetOrder()
    {
    }

    /**
     * Test case for returnOrder
     *
     * .
     *
     */
    public function testReturnOrder()
    {
    }
}
